apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-react
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-react
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-react
    spec:
      containers:
        - name: react
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 5
          securityContext:
            runAsUser: 1001
            fsGroup: 1001